name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby 3.2
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.2.x

    - name: Install dependencies
      run: make install

    - name: Run check
      run: make lint
